#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
case "$1" in
	firewall)
		iptables -F
		iptables -X
		iptables -Z
		iptables -t nat -F
		iptables -t nat -X
		iptables -t mangle -F
		iptables -t mangle -X
		iptables -P INPUT ACCEPT
		iptables -P FORWARD ACCEPT
		iptables -P OUTPUT ACCEPT
		;;

	limpieza)
		history -c
		#rm -rf /var/cache/*
		rm -rf /var/cache/polipo/*
		rm -rf /root/.local/share/Trash/*
		rm -rf /home/*/.local/share/Trash/*
		rm -rf /home/*/.cache/*
		apt-get clean
		apt-get autoclean
		apt-get autoremove
		;;

	iceweasel)
		rm -rf /home/*/.mozilla/*
		;;

	paquetes)
		rm -f /var/lib/dpkg/lock
		rm -f /var/cache/apt/archives/lock
		apt -q update
		apt-get -y --force-yes install
		apt-get -y autoremove
		apt -y purge $(deborphan)
		dpkg --configure -a
		#dpkg-reconfigure -a
		;;

	xfce)
		xfce4-panel --quit
		pkill xfconfd
		rm -rf ~/.cache/sessions
		rm -rf ~/.config/xfce4
		xfce4-panel
		reboot
		;;

	mate)
		gconftool-2 –shutdown
		pkill mate-panel
		rm -rf ~/.gconf/apps/panel
		reboot
		;;

	cinnamon)
		gsettings reset-recursively org.cinnamon
		cinnamon --replace
		cinnamon r
		reboot
		;;

	lxde)
		lxpanelctl restart
		;;
		
	locales)	
		apt-get install --reinstall locales
		dpkg-reconfigure locales
		;;
		
	openbox)
		openbox --reconfigure
		openbox --restart
		;;
		
	gnome)
		gconftool-2 --recursive-unset /apps/panel
		rm -rf ~/.gconf/apps/panel
		pkill gnome-panel
		;;
	
	reinstall)	
		# reinstalar TODO y reconfigura automáticamente
		# Esto puede llevar tiempo. (usar con precaución)
		dpkg-reconfigure -phigh -a 
		;;

	*)
            	echo "USO: $(basename $0) {cinnamon|iceweasel|firewall|gnome|limpieza|locales|lxde|mate|openbox|paquetes|reinstall|xfce}"
		;;

esac
rm -f /run/$(basename $0).pid
exit 0
